package com.fiften.news.model;

public class Collection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.collection_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.user_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer newsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.collection_id
     *
     * @return the value of collection.collection_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.collection_id
     *
     * @param collectionId the value for collection.collection_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.user_id
     *
     * @return the value of collection.user_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.user_id
     *
     * @param userId the value for collection.user_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.news_id
     *
     * @return the value of collection.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.news_id
     *
     * @param newsId the value for collection.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }
}