package com.fiften.news.model;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.user_name
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.type
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.user_name
     *
     * @return the value of manager.user_name
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.user_name
     *
     * @param userName the value for manager.user_name
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.type
     *
     * @return the value of manager.type
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.type
     *
     * @param type the value for manager.type
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }
}