package com.fiften.news.model;

public class Media {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.user_name
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.email
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.password
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.apply_qualification
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String applyQualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.check_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.available_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String availableStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.media_id
     *
     * @return the value of media.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.media_id
     *
     * @param mediaId the value for media.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.user_name
     *
     * @return the value of media.user_name
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.user_name
     *
     * @param userName the value for media.user_name
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.email
     *
     * @return the value of media.email
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.email
     *
     * @param email the value for media.email
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.password
     *
     * @return the value of media.password
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.password
     *
     * @param password the value for media.password
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.apply_qualification
     *
     * @return the value of media.apply_qualification
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getApplyQualification() {
        return applyQualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.apply_qualification
     *
     * @param applyQualification the value for media.apply_qualification
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setApplyQualification(String applyQualification) {
        this.applyQualification = applyQualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.check_status
     *
     * @return the value of media.check_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.check_status
     *
     * @param checkStatus the value for media.check_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.available_status
     *
     * @return the value of media.available_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getAvailableStatus() {
        return availableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.available_status
     *
     * @param availableStatus the value for media.available_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setAvailableStatus(String availableStatus) {
        this.availableStatus = availableStatus;
    }
}