package com.fiften.news.model;

public class NewsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.title
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.key
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.submit_Date
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String submitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.publish_Date
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String publishDate;

    private  String detail;

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.ID
     *
     * @return the value of news_detail.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.ID
     *
     * @param id the value for news_detail.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.media_id
     *
     * @return the value of news_detail.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.media_id
     *
     * @param mediaId the value for news_detail.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.title
     *
     * @return the value of news_detail.title
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.title
     *
     * @param title the value for news_detail.title
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.key
     *
     * @return the value of news_detail.key
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.key
     *
     * @param key the value for news_detail.key
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.submit_Date
     *
     * @return the value of news_detail.submit_Date
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.submit_Date
     *
     * @param submitDate the value for news_detail.submit_Date
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setSubmitDate(String submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.publish_Date
     *
     * @return the value of news_detail.publish_Date
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.publish_Date
     *
     * @param publishDate the value for news_detail.publish_Date
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }
}