package com.fiften.news.model;

public class NewsManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.audit_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.audit_result
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String auditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.publish_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.reject_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String rejectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_manage.report_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String reportStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.ID
     *
     * @return the value of news_manage.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.ID
     *
     * @param id the value for news_manage.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.news_id
     *
     * @return the value of news_manage.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.news_id
     *
     * @param newsId the value for news_manage.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.audit_status
     *
     * @return the value of news_manage.audit_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.audit_status
     *
     * @param auditStatus the value for news_manage.audit_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.audit_result
     *
     * @return the value of news_manage.audit_result
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getAuditResult() {
        return auditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.audit_result
     *
     * @param auditResult the value for news_manage.audit_result
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.publish_status
     *
     * @return the value of news_manage.publish_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.publish_status
     *
     * @param publishStatus the value for news_manage.publish_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.reject_status
     *
     * @return the value of news_manage.reject_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getRejectStatus() {
        return rejectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.reject_status
     *
     * @param rejectStatus the value for news_manage.reject_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setRejectStatus(String rejectStatus) {
        this.rejectStatus = rejectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_manage.report_status
     *
     * @return the value of news_manage.report_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_manage.report_status
     *
     * @param reportStatus the value for news_manage.report_status
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setReportStatus(String reportStatus) {
        this.reportStatus = reportStatus;
    }
}