package com.fiften.news.model;

public class NewsDetailWithBLOBs extends NewsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.detail
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.news_image
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private byte[] newsImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.detail
     *
     * @return the value of news_detail.detail
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.detail
     *
     * @param detail the value for news_detail.detail
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.news_image
     *
     * @return the value of news_detail.news_image
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public byte[] getNewsImage() {
        return newsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.news_image
     *
     * @param newsImage the value for news_detail.news_image
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setNewsImage(byte[] newsImage) {
        this.newsImage = newsImage;
    }
}