package com.fiften.news.model;

public class NewsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.ID
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.media_id
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.title
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.key
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private String news_key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.submit_Date
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private String submitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.publish_Date
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private String publishDate;




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.detail
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.news_image
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    private String newsImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.ID
     *
     * @return the value of news_detail.ID
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.ID
     *
     * @param id the value for news_detail.ID
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.media_id
     *
     * @return the value of news_detail.media_id
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.media_id
     *
     * @param mediaId the value for news_detail.media_id
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.title
     *
     * @return the value of news_detail.title
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.title
     *
     * @param title the value for news_detail.title
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.key
     *
     * @return the value of news_detail.key
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public String getKey() {
        return news_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.key
     *
     * @param news_key the value for news_detail.key
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setKey(String news_key) {
        this.news_key = news_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.submit_Date
     *
     * @return the value of news_detail.submit_Date
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public String getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.submit_Date
     *
     * @param submitDate the value for news_detail.submit_Date
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setSubmitDate(String submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.publish_Date
     *
     * @return the value of news_detail.publish_Date
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.publish_Date
     *
     * @param publishDate the value for news_detail.publish_Date
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.detail
     *
     * @return the value of news_detail.detail
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.detail
     *
     * @param detail the value for news_detail.detail
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.news_image
     *
     * @return the value of news_detail.news_image
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public String getNewsImage() {
        return newsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.news_image
     *
     * @param newsImage the value for news_detail.news_image
     *
     * @mbggenerated Wed Jan 08 16:32:46 CST 2020
     */
    public void setNewsImage(String newsImage) {
        this.newsImage = newsImage;
    }
}