package com.fiften.news.model;

public class ReportList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.reason
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.ID
     *
     * @return the value of report_list.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.ID
     *
     * @param id the value for report_list.ID
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.media_id
     *
     * @return the value of report_list.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.media_id
     *
     * @param mediaId the value for report_list.media_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.news_id
     *
     * @return the value of report_list.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.news_id
     *
     * @param newsId the value for report_list.news_id
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.reason
     *
     * @return the value of report_list.reason
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.reason
     *
     * @param reason the value for report_list.reason
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}