package com.fiften.news.dao;

import com.fiften.news.model.Media;
import com.fiften.news.model.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface MediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    int deleteByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    int insert(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    int insertSelective(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    Media selectByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    int updateByPrimaryKeySelective(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated Tue Jan 07 19:18:18 CST 2020
     */
    int updateByPrimaryKey(Media record);

    Media selectMediaByUserNameAndPassword(Media  media);

    List<Media> selectAllNotAvailableMedia();

    Media selectByEamil(@Param("email") String email);

    List<Media> selectAllAvailableMedia();

    int selectIdByUserName(String userName);


}